/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module full(a, b, ci, s, co);
  input a;
  input b;
  wire c;
  input ci;
  output co;
  wire k;
  output s;
  wire s1;
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0_ (
    .A(c),
    .SLEEP(k),
    .X(co)
  );
  half ha1 (
    .a(a),
    .b(b),
    .cout(k),
    .sout(s1)
  );
  half ha2 (
    .a(s1),
    .b(ci),
    .cout(c),
    .sout(s)
  );
endmodule

module half(a, b, sout, cout);
  input a;
  input b;
  output cout;
  output sout;
  sky130_fd_sc_hd__and2_0 _0_ (
    .A(a),
    .B(b),
    .X(cout)
  );
  sky130_fd_sc_hd__xor2_1 _1_ (
    .A(a),
    .B(b),
    .X(sout)
  );
endmodule
