/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "alu.v:1" *)
module alu(A, B, op, result);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  (* src = "alu.v:2" *)
  wire _132_;
  (* src = "alu.v:2" *)
  wire _133_;
  (* src = "alu.v:2" *)
  wire _134_;
  (* src = "alu.v:2" *)
  wire _135_;
  (* src = "alu.v:2" *)
  wire _136_;
  (* src = "alu.v:2" *)
  wire _137_;
  (* src = "alu.v:2" *)
  wire _138_;
  (* src = "alu.v:2" *)
  wire _139_;
  (* src = "alu.v:3" *)
  wire _140_;
  (* src = "alu.v:3" *)
  wire _141_;
  (* src = "alu.v:3" *)
  wire _142_;
  (* src = "alu.v:3" *)
  wire _143_;
  (* src = "alu.v:3" *)
  wire _144_;
  (* src = "alu.v:3" *)
  wire _145_;
  (* src = "alu.v:3" *)
  wire _146_;
  (* src = "alu.v:3" *)
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  (* src = "alu.v:4" *)
  wire _254_;
  (* src = "alu.v:4" *)
  wire _255_;
  (* src = "alu.v:4" *)
  wire _256_;
  (* src = "alu.v:5" *)
  wire _257_;
  (* src = "alu.v:5" *)
  wire _258_;
  (* src = "alu.v:5" *)
  wire _259_;
  (* src = "alu.v:5" *)
  wire _260_;
  (* src = "alu.v:5" *)
  wire _261_;
  (* src = "alu.v:5" *)
  wire _262_;
  (* src = "alu.v:5" *)
  wire _263_;
  (* src = "alu.v:5" *)
  wire _264_;
  (* src = "alu.v:2" *)
  input [7:0] A;
  (* src = "alu.v:3" *)
  input [7:0] B;
  (* src = "alu.v:4" *)
  input [2:0] op;
  (* src = "alu.v:5" *)
  output [7:0] result;
  sky130_fd_sc_hd__clkinv_1 _265_ (
    .A(_256_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__clkinv_1 _266_ (
    .A(_141_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__clkinv_1 _267_ (
    .A(_142_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__clkinv_1 _268_ (
    .A(_136_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__clkinv_1 _269_ (
    .A(_137_),
    .Y(_191_)
  );
  sky130_fd_sc_hd__clkinv_1 _270_ (
    .A(_138_),
    .Y(_192_)
  );
  sky130_fd_sc_hd__clkinv_1 _271_ (
    .A(_139_),
    .Y(_193_)
  );
  sky130_fd_sc_hd__nor2_1 _272_ (
    .A(_132_),
    .B(_140_),
    .Y(_194_)
  );
  sky130_fd_sc_hd__nand2_1 _273_ (
    .A(_254_),
    .B(_194_),
    .Y(_195_)
  );
  sky130_fd_sc_hd__nand2_1 _274_ (
    .A(_132_),
    .B(_140_),
    .Y(_196_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _275_ (
    .A(_255_),
    .SLEEP(_256_),
    .X(_197_)
  );
  sky130_fd_sc_hd__nor2b_1 _276_ (
    .A(_194_),
    .B_N(_196_),
    .Y(_198_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _277_ (
    .A(_140_),
    .SLEEP(_254_),
    .X(_199_)
  );
  sky130_fd_sc_hd__nor2_1 _278_ (
    .A(_255_),
    .B(_187_),
    .Y(_200_)
  );
  sky130_fd_sc_hd__nor2_1 _279_ (
    .A(_255_),
    .B(_256_),
    .Y(_201_)
  );
  sky130_fd_sc_hd__a32oi_1 _280_ (
    .A1(_195_),
    .A2(_196_),
    .A3(_197_),
    .B1(_198_),
    .B2(_201_),
    .Y(_202_)
  );
  sky130_fd_sc_hd__o41ai_1 _281_ (
    .A1(_255_),
    .A2(_187_),
    .A3(_198_),
    .A4(_199_),
    .B1(_202_),
    .Y(_257_)
  );
  sky130_fd_sc_hd__nor2_1 _282_ (
    .A(_133_),
    .B(_141_),
    .Y(_203_)
  );
  sky130_fd_sc_hd__nand2_1 _283_ (
    .A(_133_),
    .B(_141_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__xnor2_1 _284_ (
    .A(_133_),
    .B(_141_),
    .Y(_205_)
  );
  sky130_fd_sc_hd__nand2b_1 _285_ (
    .A_N(_132_),
    .B(_140_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__and2_0 _286_ (
    .A(_254_),
    .B(_201_),
    .X(_207_)
  );
  sky130_fd_sc_hd__nand2_1 _287_ (
    .A(_254_),
    .B(_201_),
    .Y(_208_)
  );
  sky130_fd_sc_hd__xor2_1 _288_ (
    .A(_205_),
    .B(_206_),
    .X(_209_)
  );
  sky130_fd_sc_hd__nand2_1 _289_ (
    .A(_207_),
    .B(_209_),
    .Y(_210_)
  );
  sky130_fd_sc_hd__nor3_1 _290_ (
    .A(_255_),
    .B(_254_),
    .C(_256_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__xor2_1 _291_ (
    .A(_196_),
    .B(_205_),
    .X(_212_)
  );
  sky130_fd_sc_hd__nand2b_1 _292_ (
    .A_N(_254_),
    .B(_133_),
    .Y(_213_)
  );
  sky130_fd_sc_hd__nand3_1 _293_ (
    .A(_200_),
    .B(_205_),
    .C(_213_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__nand2_1 _294_ (
    .A(_254_),
    .B(_203_),
    .Y(_215_)
  );
  sky130_fd_sc_hd__a32oi_1 _295_ (
    .A1(_197_),
    .A2(_204_),
    .A3(_215_),
    .B1(_212_),
    .B2(_211_),
    .Y(_216_)
  );
  sky130_fd_sc_hd__nand3_1 _296_ (
    .A(_210_),
    .B(_214_),
    .C(_216_),
    .Y(_258_)
  );
  sky130_fd_sc_hd__xnor2_1 _297_ (
    .A(_134_),
    .B(_142_),
    .Y(_217_)
  );
  sky130_fd_sc_hd__o21ai_0 _298_ (
    .A1(_196_),
    .A2(_205_),
    .B1(_204_),
    .Y(_218_)
  );
  sky130_fd_sc_hd__xnor2_1 _299_ (
    .A(_217_),
    .B(_218_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__maj3_1 _300_ (
    .A(_133_),
    .B(_188_),
    .C(_206_),
    .X(_220_)
  );
  sky130_fd_sc_hd__and2_0 _301_ (
    .A(_217_),
    .B(_220_),
    .X(_221_)
  );
  sky130_fd_sc_hd__o21ai_0 _302_ (
    .A1(_217_),
    .A2(_220_),
    .B1(_207_),
    .Y(_222_)
  );
  sky130_fd_sc_hd__o21ai_0 _303_ (
    .A1(_254_),
    .A2(_134_),
    .B1(_217_),
    .Y(_223_)
  );
  sky130_fd_sc_hd__nand2b_1 _304_ (
    .A_N(_254_),
    .B(_142_),
    .Y(_224_)
  );
  sky130_fd_sc_hd__a32oi_1 _305_ (
    .A1(_200_),
    .A2(_217_),
    .A3(_224_),
    .B1(_223_),
    .B2(_197_),
    .Y(_225_)
  );
  sky130_fd_sc_hd__o21ai_0 _306_ (
    .A1(_221_),
    .A2(_222_),
    .B1(_225_),
    .Y(_226_)
  );
  sky130_fd_sc_hd__a21o_1 _307_ (
    .A1(_211_),
    .A2(_219_),
    .B1(_226_),
    .X(_259_)
  );
  sky130_fd_sc_hd__nor2_1 _308_ (
    .A(_135_),
    .B(_143_),
    .Y(_227_)
  );
  sky130_fd_sc_hd__nand2_1 _309_ (
    .A(_135_),
    .B(_143_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__nand2b_1 _310_ (
    .A_N(_227_),
    .B(_228_),
    .Y(_229_)
  );
  sky130_fd_sc_hd__maj3_1 _311_ (
    .A(_134_),
    .B(_142_),
    .C(_218_),
    .X(_230_)
  );
  sky130_fd_sc_hd__xnor2_1 _312_ (
    .A(_229_),
    .B(_230_),
    .Y(_231_)
  );
  sky130_fd_sc_hd__nand2_1 _313_ (
    .A(_211_),
    .B(_231_),
    .Y(_232_)
  );
  sky130_fd_sc_hd__maj3_1 _314_ (
    .A(_134_),
    .B(_189_),
    .C(_220_),
    .X(_233_)
  );
  sky130_fd_sc_hd__xnor2_1 _315_ (
    .A(_229_),
    .B(_233_),
    .Y(_234_)
  );
  sky130_fd_sc_hd__nand2_1 _316_ (
    .A(_197_),
    .B(_228_),
    .Y(_235_)
  );
  sky130_fd_sc_hd__a21oi_1 _317_ (
    .A1(_254_),
    .A2(_227_),
    .B1(_235_),
    .Y(_236_)
  );
  sky130_fd_sc_hd__nand2b_1 _318_ (
    .A_N(_254_),
    .B(_135_),
    .Y(_237_)
  );
  sky130_fd_sc_hd__a31oi_1 _319_ (
    .A1(_200_),
    .A2(_229_),
    .A3(_237_),
    .B1(_236_),
    .Y(_238_)
  );
  sky130_fd_sc_hd__o211ai_1 _320_ (
    .A1(_208_),
    .A2(_234_),
    .B1(_238_),
    .C1(_232_),
    .Y(_260_)
  );
  sky130_fd_sc_hd__nor2_1 _321_ (
    .A(_136_),
    .B(_144_),
    .Y(_239_)
  );
  sky130_fd_sc_hd__and2_0 _322_ (
    .A(_136_),
    .B(_144_),
    .X(_240_)
  );
  sky130_fd_sc_hd__nand2_1 _323_ (
    .A(_136_),
    .B(_144_),
    .Y(_241_)
  );
  sky130_fd_sc_hd__nor2_1 _324_ (
    .A(_239_),
    .B(_240_),
    .Y(_242_)
  );
  sky130_fd_sc_hd__maj3_1 _325_ (
    .A(_135_),
    .B(_143_),
    .C(_230_),
    .X(_243_)
  );
  sky130_fd_sc_hd__xor2_1 _326_ (
    .A(_242_),
    .B(_243_),
    .X(_244_)
  );
  sky130_fd_sc_hd__nand2_1 _327_ (
    .A(_211_),
    .B(_244_),
    .Y(_245_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _328_ (
    .A(_135_),
    .SLEEP(_143_),
    .X(_246_)
  );
  sky130_fd_sc_hd__a21oi_1 _329_ (
    .A1(_229_),
    .A2(_233_),
    .B1(_246_),
    .Y(_247_)
  );
  sky130_fd_sc_hd__xnor2_1 _330_ (
    .A(_242_),
    .B(_247_),
    .Y(_248_)
  );
  sky130_fd_sc_hd__nor2_1 _331_ (
    .A(_208_),
    .B(_248_),
    .Y(_249_)
  );
  sky130_fd_sc_hd__o21ai_0 _332_ (
    .A1(_254_),
    .A2(_190_),
    .B1(_200_),
    .Y(_250_)
  );
  sky130_fd_sc_hd__nand2_1 _333_ (
    .A(_254_),
    .B(_239_),
    .Y(_251_)
  );
  sky130_fd_sc_hd__a31oi_1 _334_ (
    .A1(_197_),
    .A2(_241_),
    .A3(_251_),
    .B1(_249_),
    .Y(_252_)
  );
  sky130_fd_sc_hd__o211ai_1 _335_ (
    .A1(_242_),
    .A2(_250_),
    .B1(_252_),
    .C1(_245_),
    .Y(_261_)
  );
  sky130_fd_sc_hd__nor2_1 _336_ (
    .A(_137_),
    .B(_145_),
    .Y(_253_)
  );
  sky130_fd_sc_hd__and2_0 _337_ (
    .A(_137_),
    .B(_145_),
    .X(_148_)
  );
  sky130_fd_sc_hd__nand2_1 _338_ (
    .A(_137_),
    .B(_145_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _339_ (
    .A(_253_),
    .SLEEP(_148_),
    .X(_150_)
  );
  sky130_fd_sc_hd__nand2b_1 _340_ (
    .A_N(_144_),
    .B(_136_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__o21ai_0 _341_ (
    .A1(_242_),
    .A2(_247_),
    .B1(_151_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__nand2_1 _342_ (
    .A(_150_),
    .B(_152_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__nand2_1 _343_ (
    .A(_207_),
    .B(_153_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__o211ai_1 _344_ (
    .A1(_254_),
    .A2(_191_),
    .B1(_200_),
    .C1(_150_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _345_ (
    .A1_N(_154_),
    .A2_N(_155_),
    .B1(_150_),
    .B2(_152_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__a21oi_1 _346_ (
    .A1(_242_),
    .A2(_243_),
    .B1(_240_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__xor2_1 _347_ (
    .A(_150_),
    .B(_157_),
    .X(_158_)
  );
  sky130_fd_sc_hd__nand2_1 _348_ (
    .A(_254_),
    .B(_253_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__a32oi_1 _349_ (
    .A1(_197_),
    .A2(_149_),
    .A3(_159_),
    .B1(_158_),
    .B2(_211_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__nand2_1 _350_ (
    .A(_156_),
    .B(_160_),
    .Y(_262_)
  );
  sky130_fd_sc_hd__nor2_1 _351_ (
    .A(_138_),
    .B(_146_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__nand2_1 _352_ (
    .A(_138_),
    .B(_146_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__nand2b_1 _353_ (
    .A_N(_161_),
    .B(_162_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__nor2_1 _354_ (
    .A(_191_),
    .B(_145_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__a21oi_1 _355_ (
    .A1(_150_),
    .A2(_152_),
    .B1(_164_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__xor2_1 _356_ (
    .A(_163_),
    .B(_165_),
    .X(_166_)
  );
  sky130_fd_sc_hd__a211oi_1 _357_ (
    .A1(_242_),
    .A2(_243_),
    .B1(_148_),
    .C1(_240_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__o21ai_0 _358_ (
    .A1(_253_),
    .A2(_167_),
    .B1(_163_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__nor3_1 _359_ (
    .A(_253_),
    .B(_163_),
    .C(_167_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__nand3b_1 _360_ (
    .A_N(_169_),
    .B(_211_),
    .C(_168_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__nand2b_1 _361_ (
    .A_N(_254_),
    .B(_138_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__nand2_1 _362_ (
    .A(_197_),
    .B(_162_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__a21oi_1 _363_ (
    .A1(_254_),
    .A2(_161_),
    .B1(_172_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__a31oi_1 _364_ (
    .A1(_200_),
    .A2(_163_),
    .A3(_171_),
    .B1(_173_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__o211ai_1 _365_ (
    .A1(_208_),
    .A2(_166_),
    .B1(_170_),
    .C1(_174_),
    .Y(_263_)
  );
  sky130_fd_sc_hd__nor2_1 _366_ (
    .A(_139_),
    .B(_147_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__nand2_1 _367_ (
    .A(_139_),
    .B(_147_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__nor2b_1 _368_ (
    .A(_175_),
    .B_N(_176_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__maj3_1 _369_ (
    .A(_192_),
    .B(_146_),
    .C(_165_),
    .X(_178_)
  );
  sky130_fd_sc_hd__xnor2_1 _370_ (
    .A(_177_),
    .B(_178_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__o31ai_1 _371_ (
    .A1(_253_),
    .A2(_163_),
    .A3(_167_),
    .B1(_162_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__xor2_1 _372_ (
    .A(_177_),
    .B(_180_),
    .X(_181_)
  );
  sky130_fd_sc_hd__nand2_1 _373_ (
    .A(_254_),
    .B(_175_),
    .Y(_182_)
  );
  sky130_fd_sc_hd__nand3_1 _374_ (
    .A(_197_),
    .B(_176_),
    .C(_182_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__o21ai_0 _375_ (
    .A1(_254_),
    .A2(_193_),
    .B1(_200_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__o21ai_0 _376_ (
    .A1(_177_),
    .A2(_184_),
    .B1(_183_),
    .Y(_185_)
  );
  sky130_fd_sc_hd__a21oi_1 _377_ (
    .A1(_211_),
    .A2(_181_),
    .B1(_185_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__o21ai_0 _378_ (
    .A1(_208_),
    .A2(_179_),
    .B1(_186_),
    .Y(_264_)
  );
  assign _132_ = A[0];
  assign _140_ = B[0];
  assign _255_ = op[1];
  assign _254_ = op[0];
  assign _256_ = op[2];
  assign result[0] = _257_;
  assign _133_ = A[1];
  assign _141_ = B[1];
  assign result[1] = _258_;
  assign _134_ = A[2];
  assign _142_ = B[2];
  assign result[2] = _259_;
  assign _135_ = A[3];
  assign _143_ = B[3];
  assign result[3] = _260_;
  assign _136_ = A[4];
  assign _144_ = B[4];
  assign result[4] = _261_;
  assign _137_ = A[5];
  assign _145_ = B[5];
  assign result[5] = _262_;
  assign _138_ = A[6];
  assign _146_ = B[6];
  assign result[6] = _263_;
  assign _139_ = A[7];
  assign _147_ = B[7];
  assign result[7] = _264_;
endmodule
